### PR TITLE
Replace hook.io with .fork()

### PR DESCRIPTION
**Pull request by indexzero**
@mmalecki Great work here, I knuckled down and wrapped up the last of the test changes. Mostly just a couple of places where we needed to be doing `.on('message'` instead of `.stdout.on('data'`. 

Please review my last two changes and merge this in. With the `fork` branches of forever and haibu I was able to get all tests passing on 0.6.6:

https://github.com/nodejitsu/forever/commits/fork
https://github.com/nodejitsu/haibu/commits/fork

```
  $ cd /haibu-carapace
  $ git fetch && git checkout fork
  $ [sudo] npm link

  $ cd /forever
  $ git fetch && git checkout fork
  $ [sudo] npm link

  $ cd /haibu
  $ git fetch && git checkout fork
  $ [sudo] npm link forever haibu-carapace
  $ npm test
```

@bmeck If you could also confirm the above that would be great.

### CODE REVIEW

**Comment by mmalecki** [comment]
Pushed a change to remove `evref` - we don't need it anymore.
@bmeck Please make `evref` a module, it's a cool thing :).

**Comment by mmalecki** [comment]
Tests pass for me. This is a great win.

**Comment by nathanaschbacher** [comment]
If you don't mind my asking.  What was the purpose of this change?  What was it about hook.io that warranted removing it?

**Comment by indexzero** [comment]
Less dependencies. Hook.io has a lot of them and it wasn't deemed necessary since the use-case here is limited to a single machine by definition.

**Comment by nathanaschbacher** [comment]
Ah, interesting.  That makes sense to me.  I was mostly asking because I have built a similar sort of distributed processing framework for Node, and I'm in the process of allowing support across machine boundaries rather than just process boundaries, and I was going to use socket.io for this purpose, but came across hook.io.  Seeing this decision here made me curious.

**Pull request merged**
