### PR TITLE
Fix for issue #6 and fix for correct 'carapace::port' event data (desired value)

### PR DESCRIPTION
**Pull request by stolsma**
[fix] Fix for issue #6 and also fix for correct 'carapace::port' event data (desired value).

### CODE REVIEW

**Comment by indexzero** [comment]
@stolsma In order for us to accept this pull-request, we need vows-based tests which reproduce the issue. We will revisit merging this in if you can provide those tests.

Thanks for all the feedback, it's been really helpful!

**Comment by stolsma** [comment]
@indexzero I understand requiring vows based test... Although it will be difficult because the problem lies in concurrent processes so reproduction is incredibly difficult !

I sometimes need to restart haibu and apps for a couple (2-3) of times to get this error so I'm not sure I can make a vows bases test that reproduces the error every time... :-(

**Comment by indexzero** [comment]
@stolsma Given the complexity of the issue, if you can provide plain node.js code which _always_ reproduces the issue we will revisit this pull-request. 

It's really a matter of policy, pulling in a fix without expanded test coverage is counter-intuitive

**Comment by stolsma** [comment]
I will pull this pull request until we found a good reproducible testscript

**Pull request closed without merging**
